module main

// Auto-generated. DO NOT EDIT. Run: v run scripts/gen_embedded.v
// Embeds all syntax YAML files into the binary so highlighting works
// even when syntax/ is not installed on disk (e.g. wax/brew installs).

fn embedded_syntax_yaml(ft string) ?string {
	return match ft {
		'PowerShell' { $embed_file('syntax/PowerShell.yaml').to_string() }
		'ada' { $embed_file('syntax/ada.yaml').to_string() }
		'apacheconf' { $embed_file('syntax/apacheconf.yaml').to_string() }
		'arduino' { $embed_file('syntax/arduino.yaml').to_string() }
		'asciidoc' { $embed_file('syntax/asciidoc.yaml').to_string() }
		'asm' { $embed_file('syntax/asm.yaml').to_string() }
		'ats' { $embed_file('syntax/ats.yaml').to_string() }
		'awk' { $embed_file('syntax/awk.yaml').to_string() }
		'b' { $embed_file('syntax/b.yaml').to_string() }
		'bat' { $embed_file('syntax/bat.yaml').to_string() }
		'c' { $embed_file('syntax/c.yaml').to_string() }
		'caddyfile' { $embed_file('syntax/caddyfile.yaml').to_string() }
		'cake' { $embed_file('syntax/cake.yaml').to_string() }
		'clojure' { $embed_file('syntax/clojure.yaml').to_string() }
		'cmake' { $embed_file('syntax/cmake.yaml').to_string() }
		'coffeescript' { $embed_file('syntax/coffeescript.yaml').to_string() }
		'colortest' { $embed_file('syntax/colortest.yaml').to_string() }
		'conky' { $embed_file('syntax/conky.yaml').to_string() }
		'cpp' { $embed_file('syntax/cpp.yaml').to_string() }
		'crontab' { $embed_file('syntax/crontab.yaml').to_string() }
		'crystal' { $embed_file('syntax/crystal.yaml').to_string() }
		'csharp' { $embed_file('syntax/csharp.yaml').to_string() }
		'css' { $embed_file('syntax/css.yaml').to_string() }
		'csx' { $embed_file('syntax/csx.yaml').to_string() }
		'cuda' { $embed_file('syntax/cuda.yaml').to_string() }
		'cython' { $embed_file('syntax/cython.yaml').to_string() }
		'd' { $embed_file('syntax/d.yaml').to_string() }
		'dart' { $embed_file('syntax/dart.yaml').to_string() }
		'default' { $embed_file('syntax/default.yaml').to_string() }
		'dockerfile' { $embed_file('syntax/dockerfile.yaml').to_string() }
		'dot' { $embed_file('syntax/dot.yaml').to_string() }
		'elixir' { $embed_file('syntax/elixir.yaml').to_string() }
		'elm' { $embed_file('syntax/elm.yaml').to_string() }
		'erb' { $embed_file('syntax/erb.yaml').to_string() }
		'erlang' { $embed_file('syntax/erlang.yaml').to_string() }
		'fish' { $embed_file('syntax/fish.yaml').to_string() }
		'forth' { $embed_file('syntax/forth.yaml').to_string() }
		'fortran' { $embed_file('syntax/fortran.yaml').to_string() }
		'freebsd-kernel' { $embed_file('syntax/freebsd-kernel.yaml').to_string() }
		'fsharp' { $embed_file('syntax/fsharp.yaml').to_string() }
		'gdscript' { $embed_file('syntax/gdscript.yaml').to_string() }
		'gemini' { $embed_file('syntax/gemini.yaml').to_string() }
		'gentoo-ebuild' { $embed_file('syntax/gentoo-ebuild.yaml').to_string() }
		'gentoo-etc-portage' { $embed_file('syntax/gentoo-etc-portage.yaml').to_string() }
		'git-commit' { $embed_file('syntax/git-commit.yaml').to_string() }
		'git-config' { $embed_file('syntax/git-config.yaml').to_string() }
		'git-rebase-todo' { $embed_file('syntax/git-rebase-todo.yaml').to_string() }
		'gleam' { $embed_file('syntax/gleam.yaml').to_string() }
		'glsl' { $embed_file('syntax/glsl.yaml').to_string() }
		'gnuplot' { $embed_file('syntax/gnuplot.yaml').to_string() }
		'go' { $embed_file('syntax/go.yaml').to_string() }
		'godoc' { $embed_file('syntax/godoc.yaml').to_string() }
		'golo' { $embed_file('syntax/golo.yaml').to_string() }
		'gomod' { $embed_file('syntax/gomod.yaml').to_string() }
		'graphql' { $embed_file('syntax/graphql.yaml').to_string() }
		'groff' { $embed_file('syntax/groff.yaml').to_string() }
		'groovy' { $embed_file('syntax/groovy.yaml').to_string() }
		'haml' { $embed_file('syntax/haml.yaml').to_string() }
		'hare' { $embed_file('syntax/hare.yaml').to_string() }
		'haskell' { $embed_file('syntax/haskell.yaml').to_string() }
		'hc' { $embed_file('syntax/hc.yaml').to_string() }
		'html' { $embed_file('syntax/html.yaml').to_string() }
		'html4' { $embed_file('syntax/html4.yaml').to_string() }
		'html5' { $embed_file('syntax/html5.yaml').to_string() }
		'ini' { $embed_file('syntax/ini.yaml').to_string() }
		'inputrc' { $embed_file('syntax/inputrc.yaml').to_string() }
		'java' { $embed_file('syntax/java.yaml').to_string() }
		'javascript' { $embed_file('syntax/javascript.yaml').to_string() }
		'jinja2' { $embed_file('syntax/jinja2.yaml').to_string() }
		'json' { $embed_file('syntax/json.yaml').to_string() }
		'jsonnet' { $embed_file('syntax/jsonnet.yaml').to_string() }
		'julia' { $embed_file('syntax/julia.yaml').to_string() }
		'justfile' { $embed_file('syntax/justfile.yaml').to_string() }
		'keymap' { $embed_file('syntax/keymap.yaml').to_string() }
		'kickstart' { $embed_file('syntax/kickstart.yaml').to_string() }
		'kotlin' { $embed_file('syntax/kotlin.yaml').to_string() }
		'kvlang' { $embed_file('syntax/kvlang.yaml').to_string() }
		'ledger' { $embed_file('syntax/ledger.yaml').to_string() }
		'lfe' { $embed_file('syntax/lfe.yaml').to_string() }
		'lilypond' { $embed_file('syntax/lilypond.yaml').to_string() }
		'lisp' { $embed_file('syntax/lisp.yaml').to_string() }
		'log' { $embed_file('syntax/log.yaml').to_string() }
		'lua' { $embed_file('syntax/lua.yaml').to_string() }
		'mail' { $embed_file('syntax/mail.yaml').to_string() }
		'makefile' { $embed_file('syntax/makefile.yaml').to_string() }
		'man' { $embed_file('syntax/man.yaml').to_string() }
		'markdown' { $embed_file('syntax/markdown.yaml').to_string() }
		'mc' { $embed_file('syntax/mc.yaml').to_string() }
		'meson' { $embed_file('syntax/meson.yaml').to_string() }
		'micro' { $embed_file('syntax/micro.yaml').to_string() }
		'mpdconf' { $embed_file('syntax/mpdconf.yaml').to_string() }
		'msbuild' { $embed_file('syntax/msbuild.yaml').to_string() }
		'nanorc' { $embed_file('syntax/nanorc.yaml').to_string() }
		'nftables' { $embed_file('syntax/nftables.yaml').to_string() }
		'nginx' { $embed_file('syntax/nginx.yaml').to_string() }
		'nim' { $embed_file('syntax/nim.yaml').to_string() }
		'nix' { $embed_file('syntax/nix.yaml').to_string() }
		'nu' { $embed_file('syntax/nu.yaml').to_string() }
		'objc' { $embed_file('syntax/objc.yaml').to_string() }
		'ocaml' { $embed_file('syntax/ocaml.yaml').to_string() }
		'octave' { $embed_file('syntax/octave.yaml').to_string() }
		'odin' { $embed_file('syntax/odin.yaml').to_string() }
		'pascal' { $embed_file('syntax/pascal.yaml').to_string() }
		'patch' { $embed_file('syntax/patch.yaml').to_string() }
		'peg' { $embed_file('syntax/peg.yaml').to_string() }
		'perl' { $embed_file('syntax/perl.yaml').to_string() }
		'php' { $embed_file('syntax/php.yaml').to_string() }
		'pkg-config' { $embed_file('syntax/pkg-config.yaml').to_string() }
		'po' { $embed_file('syntax/po.yaml').to_string() }
		'pony' { $embed_file('syntax/pony.yaml').to_string() }
		'pov' { $embed_file('syntax/pov.yaml').to_string() }
		'privoxy-action' { $embed_file('syntax/privoxy-action.yaml').to_string() }
		'privoxy-config' { $embed_file('syntax/privoxy-config.yaml').to_string() }
		'privoxy-filter' { $embed_file('syntax/privoxy-filter.yaml').to_string() }
		'proto' { $embed_file('syntax/proto.yaml').to_string() }
		'prql' { $embed_file('syntax/prql.yaml').to_string() }
		'puppet' { $embed_file('syntax/puppet.yaml').to_string() }
		'python2' { $embed_file('syntax/python2.yaml').to_string() }
		'python3' { $embed_file('syntax/python3.yaml').to_string() }
		'r' { $embed_file('syntax/r.yaml').to_string() }
		'raku' { $embed_file('syntax/raku.yaml').to_string() }
		'reST' { $embed_file('syntax/reST.yaml').to_string() }
		'renpy' { $embed_file('syntax/renpy.yaml').to_string() }
		'rpmspec' { $embed_file('syntax/rpmspec.yaml').to_string() }
		'ruby' { $embed_file('syntax/ruby.yaml').to_string() }
		'rust' { $embed_file('syntax/rust.yaml').to_string() }
		'sage' { $embed_file('syntax/sage.yaml').to_string() }
		'scad' { $embed_file('syntax/scad.yaml').to_string() }
		'scala' { $embed_file('syntax/scala.yaml').to_string() }
		'sed' { $embed_file('syntax/sed.yaml').to_string() }
		'sh' { $embed_file('syntax/sh.yaml').to_string() }
		'sls' { $embed_file('syntax/sls.yaml').to_string() }
		'smalltalk' { $embed_file('syntax/smalltalk.yaml').to_string() }
		'solidity' { $embed_file('syntax/solidity.yaml').to_string() }
		'sql' { $embed_file('syntax/sql.yaml').to_string() }
		'stata' { $embed_file('syntax/stata.yaml').to_string() }
		'svelte' { $embed_file('syntax/svelte.yaml').to_string() }
		'swift' { $embed_file('syntax/swift.yaml').to_string() }
		'systemd' { $embed_file('syntax/systemd.yaml').to_string() }
		'tcl' { $embed_file('syntax/tcl.yaml').to_string() }
		'terraform' { $embed_file('syntax/terraform.yaml').to_string() }
		'tex' { $embed_file('syntax/tex.yaml').to_string() }
		'toml' { $embed_file('syntax/toml.yaml').to_string() }
		'twig' { $embed_file('syntax/twig.yaml').to_string() }
		'typescript' { $embed_file('syntax/typescript.yaml').to_string() }
		'v' { $embed_file('syntax/v.yaml').to_string() }
		'vala' { $embed_file('syntax/vala.yaml').to_string() }
		'verilog' { $embed_file('syntax/verilog.yaml').to_string() }
		'vhdl' { $embed_file('syntax/vhdl.yaml').to_string() }
		'vi' { $embed_file('syntax/vi.yaml').to_string() }
		'vue' { $embed_file('syntax/vue.yaml').to_string() }
		'xml' { $embed_file('syntax/xml.yaml').to_string() }
		'xresources' { $embed_file('syntax/xresources.yaml').to_string() }
		'yaml' { $embed_file('syntax/yaml.yaml').to_string() }
		'yum' { $embed_file('syntax/yum.yaml').to_string() }
		'zig' { $embed_file('syntax/zig.yaml').to_string() }
		'zscript' { $embed_file('syntax/zscript.yaml').to_string() }
		'zsh' { $embed_file('syntax/zsh.yaml').to_string() }
		else { none }
	}
}
